# 2.3 尺寸、存储偏移与步长

In [1]:
import torch

points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point.storage_offset()

2

In [2]:
second_point.size()

torch.Size([2])

In [3]:
second_point.shape

torch.Size([2])

In [4]:
points.stride()

(2, 1)

In [5]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point.size()

torch.Size([2])

In [6]:
second_point.storage_offset()

2

In [7]:
second_point.stride()

(1,)

In [8]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 1.,  4.],
        [10.,  1.],
        [ 3.,  5.]])

In [9]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

## 矩阵转置

In [10]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [11]:
points_t = points.t()
points_t

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [12]:
id(points.storage()) == id(points_t.storage())

True

In [13]:
points.stride()

(2, 1)

In [14]:
points_t.stride()

(1, 2)

## 多维数组转置

In [15]:
some_tensor = torch.ones(3, 4, 5)
some_tensor.shape, some_tensor.stride()

(torch.Size([3, 4, 5]), (20, 5, 1))

In [16]:
some_tensor_t = some_tensor.transpose(0, 2)
some_tensor_t.shape, some_tensor_t.stride()

(torch.Size([5, 4, 3]), (1, 5, 20))

## 张量的连续性

In [17]:
points.is_contiguous(), points_t.is_contiguous()

(True, False)

In [18]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points_t = points.t()
points_t

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [19]:
points_t.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

In [20]:
points_t.stride()

(1, 2)

In [21]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [22]:
points_t_cont.stride()

(3, 1)

In [23]:
points_t_cont.storage()

 1.0
 2.0
 3.0
 4.0
 1.0
 5.0
[torch.FloatStorage of size 6]