# 2.7 序列化张量

In [1]:
import torch

points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [2]:
torch.save(points, '../../data/chapter2/ourpoints.t')

In [3]:
!ls ../../data/chapter2/

ourpoints.hdf5 ourpoints.t


In [4]:
with open('../../data/chapter2/ourpoints.t','wb') as f:
    torch.save(points, f)

In [5]:
points = torch.load('../../data/chapter2/ourpoints.t')

In [6]:
with open('../../data/chapter2/ourpoints.t','rb') as f:
    points = torch.load(f)

## HDF5

In [7]:
import h5py

f = h5py.File('../../data/chapter2/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [8]:
!ls ../../data/chapter2/

ourpoints.hdf5 ourpoints.t


In [9]:
f = h5py.File('../../data/chapter2/ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[1:]
last_points

array([[ 2.,  1.],
       [ 3.,  5.]], dtype=float32)

In [10]:
last_points = torch.from_numpy(dset[1:])
f.close()
last_points

tensor([[2., 1.],
        [3., 5.]])

In [11]:
# last_points = torch.from_numpy(dset[1:]) # 会报错, 因为f已经关了